### ISSUE TITLE
Sitio Web Bocetos preliminares portada

### ISSUE THREAD

**Issue by nauscarriaga** [soporteitsos/itsosSitioWebITsos#1]
**CAPTURA PORTADA PRINCIPAL** 
![foto1](https://user-images.githubusercontent.com/48842955/77685891-e3fe2b80-6f7a-11ea-932a-78b70f45ccd8.jpeg)

CAPTURA SIGUIENTE 
![foto2](https://user-images.githubusercontent.com/48842955/77685905-ec566680-6f7a-11ea-9ad0-06cd4c41a95e.jpeg)

**Comment by nauscarriaga** [comment]
Estimados, estos son los bocetos de la pagina principal en la cual esta trabajando Ruben.

**Comment by soporteitsos** [comment]
Dejo el link en Alta https://www.google.com/url?q=https://projects.invisionapp.com/freehand/document/4RPwuhdQC&sa=D&source=hangouts&ust=1588106565642000&usg=AFQjCNFTw2g4XXvMCfDkugEqZCNN-yk1dQ
